-- MySQL Script generated by MySQL Workbench
-- mié 29 ago 2018 14:32:15 -04
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuarios` (
  `idusuarios` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `login` VARCHAR(20) NOT NULL,
  `clave` VARCHAR(100) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `img` VARCHAR(45) NULL,
  `condicion` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`idusuarios`),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`permisos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`permisos` (
  `idpermisos` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idpermisos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuarios_permisos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuarios_permisos` (
  `idusuarios_permisos` INT NOT NULL AUTO_INCREMENT,
  `idusuarios` INT NOT NULL,
  `idpermisos` INT NOT NULL,
  PRIMARY KEY (`idusuarios_permisos`),
  INDEX `fk_usuarios_permisos_usuarios_idx` (`idusuarios` ASC),
  INDEX `fk_usuarios_permisos_permisos_idx` (`idpermisos` ASC),
  CONSTRAINT `fk_usuarios_permisos_usuarios`
    FOREIGN KEY (`idusuarios`)
    REFERENCES `mydb`.`usuarios` (`idusuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuarios_permisos_permisos`
    FOREIGN KEY (`idpermisos`)
    REFERENCES `mydb`.`permisos` (`idpermisos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`items` (
  `iditems` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `barcode` VARCHAR(45) NULL,
  `precio_nac` DECIMAL(30,2) NOT NULL,
  `precio_usd` DECIMAL(30,2) NOT NULL,
  `precio_depre` DECIMAL(30,2) NOT NULL,
  `stock` DECIMAL(30,2) NOT NULL,
  `stock_min` DECIMAL(30,2) NOT NULL,
  `stock_max` DECIMAL(30,2) NOT NULL,
  `unidad` VARCHAR(5) NOT NULL,
  `detalle` VARCHAR(45) NULL,
  `img` VARCHAR(45) NULL,
  `condicion` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`iditems`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`servicios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`servicios` (
  `idservicios` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `precio_nac` DECIMAL(30,2) NOT NULL,
  `precio_usd` DECIMAL(30,2) NOT NULL,
  `precio_depre` DECIMAL(30,2) NOT NULL,
  `condicion` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`idservicios`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`centro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`centro` (
  `idcentro` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `condicion` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`idcentro`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cargos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cargos` (
  `idcargos` INT NOT NULL AUTO_INCREMENT,
  `idusuario` INT NOT NULL,
  `idcentro` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `responsable` VARCHAR(45) NOT NULL,
  `supervisor` VARCHAR(45) NOT NULL,
  `comentario` VARCHAR(100) NULL,
  `condicion` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`idcargos`),
  INDEX `fk_cargos_usuario_idx` (`idusuario` ASC),
  INDEX `fk_cargos_centro_idx` (`idcentro` ASC),
  CONSTRAINT `fk_cargos_usuario`
    FOREIGN KEY (`idusuario`)
    REFERENCES `mydb`.`usuarios` (`idusuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cargos_centro`
    FOREIGN KEY (`idcentro`)
    REFERENCES `mydb`.`centro` (`idcentro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cargos_items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cargos_items` (
  `idcargos_items` INT NOT NULL AUTO_INCREMENT,
  `idcargos` INT NOT NULL,
  `Iditems` INT NOT NULL,
  `cantidad` DECIMAL(30,2) NOT NULL,
  PRIMARY KEY (`idcargos_items`),
  INDEX `fk_cargos_items_cargos_idx` (`idcargos` ASC),
  INDEX `fk_cargos_items_items_idx` (`Iditems` ASC),
  CONSTRAINT `fk_cargos_items_cargos`
    FOREIGN KEY (`idcargos`)
    REFERENCES `mydb`.`cargos` (`idcargos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cargos_items_items`
    FOREIGN KEY (`Iditems`)
    REFERENCES `mydb`.`items` (`iditems`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ods_temp`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ods_temp` (
  `idods_temp` INT NOT NULL AUTO_INCREMENT,
  `idusuario` INT NOT NULL,
  `idcentro` INT NOT NULL,
  `comentario` VARCHAR(100) NULL,
  `responsable` VARCHAR(45) NOT NULL,
  `supervisor` VARCHAR(45) NOT NULL,
  `prioridad` TINYINT(1) NOT NULL,
  `mantenimiento` TINYINT(1) NOT NULL,
  `fecha` DATE NOT NULL,
  `condicion` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`idods_temp`),
  INDEX `fk_ods_temp_usuarios_idx` (`idusuario` ASC),
  INDEX `fk_ods_temp_centro_idx` (`idcentro` ASC),
  CONSTRAINT `fk_ods_temp_usuarios`
    FOREIGN KEY (`idusuario`)
    REFERENCES `mydb`.`usuarios` (`idusuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ods_temp_centro`
    FOREIGN KEY (`idcentro`)
    REFERENCES `mydb`.`centro` (`idcentro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ods`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ods` (
  `idods` INT NOT NULL AUTO_INCREMENT,
  `idods_temp` INT NOT NULL,
  `codigo` VARCHAR(45) NOT NULL,
  `fecha` DATE NOT NULL,
  PRIMARY KEY (`idods`),
  INDEX `fk_ods_ods_temp_idx` (`idods_temp` ASC),
  CONSTRAINT `fk_ods_ods_temp`
    FOREIGN KEY (`idods_temp`)
    REFERENCES `mydb`.`ods_temp` (`idods_temp`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ods_temp_servicios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ods_temp_servicios` (
  `idot_temp_servicios` INT NOT NULL AUTO_INCREMENT,
  `idods_temp` INT NOT NULL,
  `idservicios` INT NOT NULL,
  `cantidad` DECIMAL(30,2) NOT NULL,
  PRIMARY KEY (`idot_temp_servicios`),
  INDEX `fk_ods_temp_servicios_ods_temp_idx` (`idods_temp` ASC),
  INDEX `fk_ods_temp_servicios_servicios_idx` (`idservicios` ASC),
  CONSTRAINT `fk_ods_temp_servicios_ods_temp`
    FOREIGN KEY (`idods_temp`)
    REFERENCES `mydb`.`ods_temp` (`idods_temp`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ods_temp_servicios_servicios`
    FOREIGN KEY (`idservicios`)
    REFERENCES `mydb`.`servicios` (`idservicios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`departamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`departamento` (
  `iddepartamento` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`iddepartamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`request_temp`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`request_temp` (
  `idrequest_temp` INT NOT NULL AUTO_INCREMENT,
  `idusuario` INT NOT NULL,
  `iddepartamento` INT NOT NULL,
  `idcentro` INT NOT NULL,
  `comentario` VARCHAR(100) NULL,
  `responsable` VARCHAR(45) NOT NULL,
  `supervisor` VARCHAR(45) NOT NULL,
  `prioridad` TINYINT(1) NOT NULL,
  `calidad` TINYINT(1) NOT NULL,
  `mantenimiento` TINYINT(1) NOT NULL,
  `fecha` DATE NOT NULL,
  `condicion` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`idrequest_temp`),
  INDEX `fk_request_temp_usuarios_idx` (`idusuario` ASC),
  INDEX `fk_request_temp_departamento_idx` (`iddepartamento` ASC),
  INDEX `fk_request_temp_centro_idx` (`idcentro` ASC),
  CONSTRAINT `fk_request_temp_usuarios`
    FOREIGN KEY (`idusuario`)
    REFERENCES `mydb`.`usuarios` (`idusuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_request_temp_departamento`
    FOREIGN KEY (`iddepartamento`)
    REFERENCES `mydb`.`departamento` (`iddepartamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_request_temp_centro`
    FOREIGN KEY (`idcentro`)
    REFERENCES `mydb`.`centro` (`idcentro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`request_op`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`request_op` (
  `idrequest_op` INT NOT NULL AUTO_INCREMENT,
  `idrequest_temp` INT NOT NULL,
  `codigo` VARCHAR(45) NOT NULL,
  `fecha` DATE NOT NULL,
  PRIMARY KEY (`idrequest_op`),
  INDEX `fk_request_op_request_temp_idx` (`idrequest_temp` ASC),
  CONSTRAINT `fk_request_op_request_temp`
    FOREIGN KEY (`idrequest_temp`)
    REFERENCES `mydb`.`request_temp` (`idrequest_temp`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`request_items_temp`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`request_items_temp` (
  `idrequest_items_temp` INT NOT NULL AUTO_INCREMENT,
  `idrequest_temp` INT NOT NULL,
  `iditem` INT NOT NULL,
  `cantidad` DECIMAL(30,2) NOT NULL,
  PRIMARY KEY (`idrequest_items_temp`),
  INDEX `fk_request_items_items_idx` (`iditem` ASC),
  INDEX `fk_request_items_request_temp_idx` (`idrequest_temp` ASC),
  CONSTRAINT `fk_request_items_items`
    FOREIGN KEY (`iditem`)
    REFERENCES `mydb`.`items` (`iditems`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_request_items_request_temp`
    FOREIGN KEY (`idrequest_temp`)
    REFERENCES `mydb`.`request_temp` (`idrequest_temp`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`request_mtto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`request_mtto` (
  `idrequest_op` INT NOT NULL AUTO_INCREMENT,
  `idrequest_temp` INT NOT NULL,
  `codigo` VARCHAR(45) NOT NULL,
  `fecha` DATE NOT NULL,
  PRIMARY KEY (`idrequest_op`),
  INDEX `fk_request_op_request_temp_idx` (`idrequest_temp` ASC),
  CONSTRAINT `fk_request_op_request_temp0`
    FOREIGN KEY (`idrequest_temp`)
    REFERENCES `mydb`.`request_temp` (`idrequest_temp`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`requestS_temp`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`requestS_temp` (
  `idrequest_temp` INT NOT NULL AUTO_INCREMENT,
  `idusuario` INT NOT NULL,
  `iddepartamento` INT NOT NULL,
  `idcentro` INT NOT NULL,
  `comentario` VARCHAR(100) NULL,
  `responsable` VARCHAR(45) NOT NULL,
  `supervisor` VARCHAR(45) NOT NULL,
  `prioridad` TINYINT(1) NOT NULL,
  `calidad` TINYINT(1) NOT NULL,
  `mantenimiento` TINYINT(1) NOT NULL,
  `fecha` DATE NOT NULL,
  `condicion` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`idrequest_temp`),
  INDEX `fk_request_temp_usuarios_idx` (`idusuario` ASC),
  INDEX `fk_request_temp_departamento_idx` (`iddepartamento` ASC),
  INDEX `fk_request_temp_centro_idx` (`idcentro` ASC),
  CONSTRAINT `fk_request_temp_usuarios0`
    FOREIGN KEY (`idusuario`)
    REFERENCES `mydb`.`usuarios` (`idusuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_request_temp_departamento0`
    FOREIGN KEY (`iddepartamento`)
    REFERENCES `mydb`.`departamento` (`iddepartamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_request_temp_centro0`
    FOREIGN KEY (`idcentro`)
    REFERENCES `mydb`.`centro` (`idcentro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`request_services_temp`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`request_services_temp` (
  `idrequest_services_temp` INT NOT NULL AUTO_INCREMENT,
  `idrequestS_temp` INT NOT NULL,
  `idservicios` INT NOT NULL,
  `cantidad` DECIMAL(30,2) NOT NULL,
  PRIMARY KEY (`idrequest_services_temp`),
  INDEX `fk_request_services_temp_services_idx` (`idservicios` ASC),
  INDEX `fk_request_services_requestS_temp_idx` (`idrequestS_temp` ASC),
  CONSTRAINT `fk_request_services_temp_services`
    FOREIGN KEY (`idservicios`)
    REFERENCES `mydb`.`servicios` (`idservicios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_request_services_requestS_temp`
    FOREIGN KEY (`idrequestS_temp`)
    REFERENCES `mydb`.`requestS_temp` (`idrequest_temp`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`requestS_op`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`requestS_op` (
  `idrequestS_op` INT NOT NULL AUTO_INCREMENT,
  `idrequestS_temp` INT NOT NULL,
  `codigo` VARCHAR(45) NOT NULL,
  `fecha` DATE NOT NULL,
  PRIMARY KEY (`idrequestS_op`),
  INDEX `fk_requestS_op_requestS_temp_idx` (`idrequestS_temp` ASC),
  CONSTRAINT `fk_requestS_op_requestS_temp`
    FOREIGN KEY (`idrequestS_temp`)
    REFERENCES `mydb`.`requestS_temp` (`idrequest_temp`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`requestS_mtto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`requestS_mtto` (
  `idrequestS_mtto` INT NOT NULL AUTO_INCREMENT,
  `idrequestS_temp` INT NOT NULL,
  `codigo` VARCHAR(45) NOT NULL,
  `fecha` DATE NOT NULL,
  PRIMARY KEY (`idrequestS_mtto`),
  INDEX `fk_requestS_op_requestS_temp_idx` (`idrequestS_temp` ASC),
  CONSTRAINT `fk_requestS_op_requestS_temp0`
    FOREIGN KEY (`idrequestS_temp`)
    REFERENCES `mydb`.`requestS_temp` (`idrequest_temp`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`formatos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`formatos` (
  `idcalidad` INT NOT NULL,
  `titulo` VARCHAR(45) NULL,
  `codigo` VARCHAR(45) NOT NULL,
  `fecha` DATE NOT NULL,
  `revision` INT NOT NULL,
  PRIMARY KEY (`idcalidad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`clientes` (
  `idcliente` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `nfiscal` BIGINT NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `telefono` BIGINT NOT NULL,
  `condicion` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`idcliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`proveedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`proveedores` (
  `idproveedor` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `nfiscal` BIGINT NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `telefono` BIGINT NOT NULL,
  `condicion` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`idproveedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pcs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pcs` (
  `idpsc` INT NOT NULL AUTO_INCREMENT,
  `idproveedor` INT NOT NULL,
  `codigo` VARCHAR(45) NOT NULL,
  `fecha` DATE NOT NULL,
  `precio_subtotal` DECIMAL(30,2) NOT NULL,
  `precio_total` DECIMAL(30,2) NOT NULL,
  `condicion` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`idpsc`),
  INDEX `fk_pcs_proveedor_idx` (`idproveedor` ASC),
  CONSTRAINT `fk_pcs_proveedor`
    FOREIGN KEY (`idproveedor`)
    REFERENCES `mydb`.`proveedores` (`idproveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pcs_items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pcs_items` (
  `idpcs_items` INT NOT NULL AUTO_INCREMENT,
  `idpcs` INT NOT NULL,
  `Iditem` INT NOT NULL,
  `idservicio` INT NOT NULL,
  `cantidad` INT NOT NULL,
  `precio` DECIMAL(30,2) NOT NULL,
  `precio_total` DECIMAL(30,2) NOT NULL,
  `comentario` VARCHAR(45) NULL,
  `condicion` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`idpcs_items`),
  INDEX `fk_pcs_items_pcs_idx` (`idpcs` ASC),
  CONSTRAINT `fk_pcs_items_pcs`
    FOREIGN KEY (`idpcs`)
    REFERENCES `mydb`.`pcs` (`idpsc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
